version: '3.8'

services: 
    mysqldb:
        image: mysql:latest
        environment: 
        - MYSQL_ROOT_PASSWORD=admin
        volumes: 
        - ./init:/docker-entrypoint-initdb.d
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
    
    docker-python:
        build:
            context: .
        ports:
        - 5000:5000
        depends_on: 
            - mysqldb

volumes: 
    mysqlVolume:
    mysqlConfig: